name: GitHub Actions Workflow Test
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/*.yaml'
      - '.github/workflows/*.yml'
defaults:
  run:
    # bashのpipefailオプションを有効化
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  github-actions-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout source
        uses: actions/checkout@v4
      - name: setup golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: install actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@latest
      - name: run GitHub Actions workflow Linter
        run: actionlint
