name: Node Test
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "*.js"
      - "**/*.js"
      - "*.mjs"
      - "**/*.mjs"
      - "*.ts"
      - "**/*.ts"
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  nodejs-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout source
        uses: actions/checkout@v4
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
      - name: install npm packages
        run: npm install
      - name: run eslint
        run: npm run lint
      - name: run jest
        run: npm test
